### PR TITLE
Choose protocol automatically

### PR DESCRIPTION
**Pull request by ipincamp**
I have tried various error handling, this is probably the most effective in my opinion. looking at your previous code, the error callback is still not caught properly, for protocols that can't run by declaring at the beginning of the code, the nested function here aims to automatically select the protocol (if http can't be used, it automatically switches to https, if both errors, then it is returned ).

Thank you (^_^)

### CODE REVIEW

**Comment by ipincamp** [comment]
Example:
I entered the url **http://bit.ly/3pbjnIq**, it should be if forced to use http an error will occur because the redirect uses https.

**Review by xaliazhar — CHANGES_REQUESTED** [review]
Let me edit

**Review by xaliazhar — CHANGES_REQUESTED** [review]
How about this?

**Comment by aliazhar-id** [comment]
Thanks @ipincamp

**Review by Nesrena2014 — APPROVED** [review]

**Pull request merged**
